### ISSUE TITLE
WTP wifi when connecting to WTP

### ISSUE THREAD

**Issue by Giwrgosyea** [5g-empower/empower-lvnf-agent#3]
We successfully archived to connect the WTPs and CPP with the controller but not the clients with the WTPs. The clients could not connect to WTPs because there is not any empower wifi network available. This happens only when the WTPs are connected to the CPP.
Do we need to configure anything more to the CPP or WTP ?

**Comment by rriggio** [comment]
No, the CPP should work like normal switches. Did you connect the OVS in
the CPP with an OF controlelr? if so did you load the learning switch
application on the OF controller?

**Comment by Giwrgosyea** [comment]
I followed your empower network installation. The cpp is connected to the empower-runtime controller.
Which application are you referring to?

**Comment by Giwrgosyea** [comment]
I fixed this error. But now all the clients have IP but could not connect to internet.
